fast_exponentiation_C++.cpp
fast exponentiation code in c++.
=> fast exponentiation code added in c++

is_prime.cs
=> added isprime C#

palindrome_or_not_palindrome_python.py, triangle_pattern_python.py
In triangle pattern made it 2 in 1 triangle pattern. In which by the help of 1 code can print 2 types of triangle pattern just by make very small change in 1st code. 
Made palindrome more understandable and user input type
=> 2 in 1 triangle pattern

FibonacciSeries.c
Author: Carpiz Trenuela
Github: https://github.com/capriz
=> Create FibonacciSeries in Turbo C

RatInAMaze.cpp
Added a C++ code that solves the 'Rat in a Maze' algorithm using backtracking.
=> Added 'Rat in a Maze' Algorithm

Kruskal.cpp
=> added kruskal program to find minimum paths

primes_range.c
Print Prime numbers from 2 to the number using SOE[Optimised Algorithm]. i.e Time Complexity : O(log n)
=> Print Prime numbers from 2 to the number using SOE[Optimised Algorithm].

two_pointer.cpp
Hey, I am a beginner in open source development and I found your repo so I made my pull request.
Cheers!
=> added two pointer algorithm with two sum problem

QuickSort.py
The quick sort algorithm is added in this pull request.
=> Added Quick sort algorithm

Insertion_Sort.cpp
Adding implementation of insertion code with comments
=> Added implementation of insertion sort in cpp

castle.py
an interactive story mode game made using python
=> Added a python game

create_octagon.py, factorial.py
It's a python program to print a octagon. It takes user input to create a Octagon
=> Create a program to print Octagon

Largest, Smallest number in an array of numbers (Python)
Simple logic to determine the smallest and the largest number from an array of numbers. The list is taken as an input using the split() function, hence the elements get stored as strings. Later during comparision, the individual elements are converted into int insitu and the smallest and largest numbers are found.
=> Create Largest, Smallest number in an array of numbers (Python)

Pattern for n rows.c
This algorithm produces stars which are equal to the number of rows.
=> Added an Algorithm

Sum_of_digits.c
It finds the sum of all digits in integer n given by the user.
=> Sum_of_Digits

Vigenere Cipher.py
this is an alphabet encryption method
=> Vigenere Cipher Code - Python

armstrong-number.cpp
-Added Armstrong-number program in Cpp.
=> added Armstrong-number

Cutting a Rod
Given a rod of length n inches and an array of prices that contains prices of all pieces of size smaller than n. Determine the maximum value obtainable by cutting up the rod and selling the pieces.
=> Create Cutting a Rod

graph_of_cities_using_map.cpp
Created a graph between cities using a map. Sometimes questions have been asked in coding rounds based on this logic.
=> created a graph of cities using a map.

Matrix_operations.py
Python program that takes user input in form of two matrices and performs matrix addition and multiplication
=> Matrix_Operations.py

Stack_Data_Structure.cpp
Added a C++ Code for Stack Data Structure
=> Added a Stack Data Structure Program in C++

randomNumGenGuessGame.cs
Proposed adding a game that generates a random number between 0 and 100 and gives you 10 tries to guess it.
=> Random number generator guessing game

Invert Binary Tree.cpp
https://leetcode.com/problems/invert-binary-tree/
=> LeetCode 226

Binary_Exponentiation.cpp, LCM_Eulers_Lemma.cpp
Added algorithms in CPP to calculate LCM using Eulers Lemma in best possible complexity and also added Custom Binary Exponentiation more accurate than "pow" method of CPP.
=> Added LCM and custom Binary Exponentiation

Longest Repeated Subsequence.cpp
Given a string, print the longest repeating subsequence such that the two subsequence don’t have same string character at same position, i.e., any i’th character in the two subsequences shouldn’t have the same index in the original string.
=> Create Longest Repeated Subsequence.cpp

IntegerNumberToRomanNumeral.java
I have added a code in Java to conver the integer numeral to roman form
=> Added a new code in java for converting a Integer to Roman Numberal

Convert Into Letter.py
This program any number convert in letter
=> Convert Into Letter

sets in cpp
=> Create sets in cpp

SaveThePrisoner.cpp
A jail has a number of prisoners and a number of treats to pass out to them. Their jailer decides the fairest way to divide the treats is to seat the prisoners around a circular table in sequentially numbered chairs. A chair number will be drawn from a hat. Beginning with the prisoner in that chair, one candy will be handed to each prisoner sequentially around the table until all have been distributed.
The jailer is playing a little joke, though. The last piece of candy looks like all the others, but it tastes awful. Here we'll determine the chair number occupied by the prisoner who will receive that candy.
=> Save the prisoner

gesture.py
This script using the convex hull defect (angle between points) method to find the number of fingers put up, and then based on that sends out a particular command like "Volume Up" etc.  Comments are added wherever required for easy understandability.
=> Gesture Recognition using Convex Hull method

Floyd Loop Detection Algorithm
I wanted to participate in hacktoberfest2020 and also share some knowledge at the same time.
=> Floyd Loop Detection Algorithm

months.java
Java Program to demonstrate the example of Switch statement where print month name for the given number.
=> Created months.java

cows_and_bulls.cpp
Cows and Bulls is an old code-breaking mind or paper and pencil game for two or more players.
=> Added Cows and Bulls written in C++

OpenMp.cpp
First code towards Parallelization.
=> OpenMp.cpp

spiral array.cpp
=> added spiral array program in cpp

MergeSort Implementatio
C program to implement Merge Sort and count the basic number of steps executed.
=> MergeSort Implementation

Template_Add.cpp
Adding Two Numbers using a template - Learning the concept of the template.
If accepted please add a label - Hacktoberfest Accepted!
Thank you!
=> Adding Two Numbers(Template)

FindPrimes.c
A C program to find the prime numbers from 2 to 100.
=> FindPrimes.c

Utopian Tree.cpp
1. Here we  are given an Utopian Tree which goes through 2 cycles of growth every year. 
2. Each spring, it doubles in height. Each summer, its height increases by 1 meter.
3. A Utopian Tree sapling with a height of 1 meter is planted at the onset of spring. 
4. We have to calculate how tall will the tree be after n growth cycles.
=> Utopian Tree Problem

JavaExample.java
Write a program in java for Pascal’s Triangle
=> Pascal’s Triangle

Destination_City_Problem.py
=> Added Destination_City_Problem.py

ShellSort.py
Python program of Shell Sort!!
=> Add Shell_Sort.py

Top_3_no_in_List.py
using this program you will able to find top 3 numbers in the list of entries.
=> Top_3_no_in_List.py

logic_operations
A program to perform AND , OR operations . hacktoberfest
=> Logic_operations

ShellSort.cpp
Herewith with this commit Shell Sort is implemented in cpp language. 
__Hacktoberfest
=> Shell Sort implemented in cpp

wordcount.py
the python scripts gives the frequency of words in a text file that the user enters.
=> Added wordcount.py

linear_search
Program for searching in array .
=> linear_search

recursive_searching
Program for recursion search .
=> recursive_searching

CPP/quickSort.cpp
Quick sort implementation in C++ using last element as pivot. Time complexity: O(nlogn) in average case.
=> Added Quick Sort

ASCII CODE, Star Pattern
=> Create ASCII CODE

multiple_search
Program for multiple searching in array .
=> multiple_search

Calculator_C++.cpp
Added Simple Arithmetic Calculator [ +, -, *, / ] in C++
=> added Calculator_C++.cpp

primeNumberInRange.py
To print prime number  for a given range easiest python code
=> Prime number

Count Occurrence in a list
=> Create Count Occurrence in a list

BinarySearch.py
A binary search algorithm in Python language has been added.
=> BinarySearch.py created

Stack/MyStack.java
created a stack in java using queue
=> add stack in java with queue

Armstrong_number.py, Selection Sort/selection_sort.py
I have added Armstrong_number.py and Selection_Sort.py program. Kindly review it.
=> Selection_Sort.py

stack_using_linkedlist
A program for implementation of stack .
=> stack_using_linkedList

FourFunctionCalculator.JAVA
Added program that takes in user input and can perform addition, subtraction, multiplication, division.
=> Added four function calculator java

DFS_graph.java
Input is taken via a txt file and after running DFS on the input, the output is displayed in a txt file.
=> added DFS_graph.java

GraphPath.java
Program to check if a path exists between the two given nodes of the graph. Input is taken via a txt file and output is displayed in the mentioned txt file.
=> added GraphPath.java

Heart Disease Predictor.ipynb
Tkinter based application for Heart Disease analysis using RandomForestRegression Machine Learning algorithm
=> Heart_disease_predictor

CircularSinglyLinkedList Insertion.cpp, double link list.cpp
A doubly linked list program in c++ language.
=> Added a doubly linked list program

ImplementingQueueUsingTwoStacks-Without_Pointers.C
Hello there,
Can you please Merge my Pull Request?
=> Queue using Stacks Without pointers by Ojas Barawal

check for prime.py, factorial using functions.py, fibonacci.py, lin eq in 2 var.py, multiply 2 sets.py, palindrome.py, prime no. list .py, simple factorial.py, sum_of_digits.py
Different programs in python for Hacktoberfest2020
=> Python Programs

BMI_Calculator.cpp
Happy to contribute, Happy Hacktober!.
=> BMI Calculator using C++

Connected Vertices in Graph
This pull request is for hacktoberfest 2020.
The program is in python language to find the vertices connected to a particular vertex in a graph.
=> Connected Vertices in Graph

Calculator
C++ program for Simple Calculator.
=> Simple Calculator

X-pattern.c
In this pattern program in C, the input string will be printed in X pattern.
=> C program is contributed.

MergeSort_python
This is a sorting program which uses merge sort algorithm to sort a list given by the user as input in python.
=> MergeSort_python

friend function in cpp
=> Create friend function in cpp

quadraticequation.py
This program will solve any quadratic equation
@namishkhanna 
Hi Nimish, 
Can you please approve my pull request.
Thanks ,
Avinash
=> Python program to solve any quadratic equation

single level directory.c
=> Create single level directory.c

Evaluate_Postfix.c
Please review my PR.I have created a program to evaluate a postfix expression entered by the user using Stack Data Structure in C.
Thank you.
=> Evaluating a Postfix Expression using Stack

PrimeNumsBetween2Nums.py
This program can print the prime numbers between the two numbers you give in the input.
=> PrimeNumsBetween2Nums

Triangle Quest.py
You are given a positive integer . Print a numerical triangle of height  like the one below:
1
22
333
4444
55555
......
Can you do it using only arithmetic operations, a single for loop and print statement?
Use no more than two lines. The first line (the for statement) is already written for you. You have to complete the print statement.
Note: Using anything related to strings will give a score of  0.
Input Format
A single line containing integer, N.
Output Format
Print  N-1 lines as explained above.
Sample Input
5
Sample Output
1
22
333
4444
=> Create Triangle Quest.py

linear queue.c
Implement linear queue using array in c.
=> Create linear queue.c

Recursive Binary Search
Added a program implementing binary search using recursion. This program has a lot of comments to make it understandable. :)
=> Recursive Binary Search

Machine Learning - Credit Card Acceptance
This model will predict whether a credit card application will be accepted based upon various data about the applicant and it gives comparison between various machine learning algorithms.
=> Machine Learning - Credit Card Acceptance

Swap two numbers using third variable.java
Program to swap two variable using third variable
=> Create Swap two numbers using third variable.java

fuzzy-search.js
it works with a large object array (data) and a target query
=> neat fuzzy search function written using lodash

sequenceChecking.java
This method can be used to check the sequential order characters and numbers in a String
=> Create a sequence checking method in JAVA

CPP/Code _ Knapsack.cpp
here i have added the code for knapsack problem in c++
=> Knapsack problem

leapyear.r
A simple program to check if a year is a leap year or not.
=> a leap year program using R

roleTheDice.py
Added role the dice program in python
=> role the dice

JAVA/ThreadPoolPerformance.java
This is the thread pool project I am studying recently
=> ThreadPoolPerformance

deque.cpp
=> Dequeue Operations

guessing_game.py
Python game to play with your pc
=> adding guessing_game

JAVA/MultiplicationTable.java
Program prints in console multiplication table to 10.
=> Add MultiplicationTable

DisplayCalender.py
this is Program to display calendar of the given month and year .
you can also take user input by simply uncommenting line 10 and 11 along with commenting line 6 and and 7 which will make you able to take user input for year and month
=> Program to display calendar

interpolation_search.py
Created a new file called interpolation_search.py which includes an implementation of the interpolation search algorithm. The user inputs a sorted array and a number and the script returns the index of the given number.
=> Add interpolation search algorithm written in python

spiral_tree_traversal.c
Spiral Printing is basically level order traversal but in spiral form .
Language used -C
=> Adding Spiral Printing of binary tree.(C)

Searching/binary_search_recursion.c
Search for an element using binary search recursively
=> binary_search_recursion.c

Hello_World.cpp
I thought this is something very basic which was missing in c++ language even after the repo to be online for long .
Contribution is not very big but i think countable as Hello World is generally the 1st code someone writes when starting.
Thanks!
=> Added HELLO_WORLD

Basics Of C#/APIs/APImysql.cs
=> Added an MySQL C# API

Keeper app/package-lock.json, Keeper app/package.json, Keeper app/public/index.html, Keeper app/public/styles.css, Keeper app/src/Footer.jsx, Keeper app/src/Header.jsx, Keeper app/src/Note.jsx, Keeper app/src/app.jsx, Keeper app/src/index.js
This file or folder is for HacktoberFest 2020. Submitted by Siddhesh Shinde.
=> Keeper Web App using React

Hotel_wiring.cpp
This was the solution of IEEExtreme question Hotel Wiring
=> Hotel Wiring IEEExtreme 2020

Calendar.cpp
Print calendar for a given year in C++
=> Added Calendar.cpp

encryption.py
encryption algo for encrypting strings with blake2b and diff SHA like SHA1, SHA256 added
run python encryption.py
=> encryption algo for encrypting string with blake2b and diff SHA added

fib_onacci.cpp
A program to find fibonacci series.
=> fib_onacci.cpp

Python/sudoku.py, oddeven.c
added odd or even program in c
=> odd or even

MatrixMultiplier.js, sortArray.js
Usage:
```
const MatrixMultiply = require('./MatrixMultiplier.js")
MatrixMultiply([[1, 0]], [[2], [2]])
```
=> Implements a matrix multiplication function in JavaScript

kmp_string_matching.cpp
This is an O(m+n) solution for string matching. where m,n are length's of 2 strings.
=> KMP Algorithm

Min_Segment_Tree.cpp
Finding the min element in a range L to R in O(logn).
=> Segment Tree for finding the min element in a range

Subset_Sum_Possible.cpp
Subset sum problem: polynomial run time solution using dp
=> Subset Sum Problem using DP

Fft.cpp
Contains code for the fast Fourier transformation algorithm.
=> Created FFT.cpp

Bfs_graph_union.cpp
BFs code and Union Code with better complexities
=> Bfs and Graph Union variations

JAVA/AVL_Tree.java
=> Create algorithm Graph AVL_Tree.java

JAVA/DFS.cpp
=> Create DFS algorithm

CPP/Kadane's Algorithm
Kadane’s algorithm is used to find out the maximum subarray sum from an array of integers.  Time complexity of above solution is O(n) and space complexity is O(1).
=> Kadane's Algorithm

reverseDoublyLinkedList.py
added a program which reverses the doubly linked list
=> added program to reverse doubly linked list

base converter gui using tkinter
thank you for giving such opportunities to beginners. here is my project which would help you to easily convert a value from one base to another in an interactive way
=> Create base converter gui using tkinter

JAVA/Check for balanced parentheses in string.java
Hope u'll merge it in your repo!!
=> Check for balanced parentheses in string

Insertionsort.py, JAVA/QuickSort.java, game club/Game_Club.py, game club/supportSystem.py
console games made with python
=> Added game glub
